sudo: required
dist: trusty
language: python
python:
- '2.7'
branches:
  only:
  - master
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y language-pack-zh-hant fonts-wqy-microhei ttf-wqy-microhei fonts-wqy-zenhei ttf-wqy-zenhei
- sudo apt-get install -y xfonts-75dpi
- wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2/wkhtmltox-0.12.2_linux-trusty-amd64.deb
- sudo dpkg -i wkhtmltox-0.12.2_linux-trusty-amd64.deb
install:
- pip install -r requirements.txt
- fc-cache -f -v
script:
- make publish
deploy:
  provider: pages
  repo:  twnanda/twnanda.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
